# Generated by Django 2.0.2 on 2018-03-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, default=None, max_digits=4)),
                ('gender', models.TextField(choices=[(None, 'Select a gender'), ('M', 'Male'), ('F', 'Female')], default=None)),
                ('birthday', models.DateField()),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camber', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rear_camber', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('front_toe', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rear_toe', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('front_pressure', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rear_pressure', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('front_weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rear_weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('front_height', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rear_height', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fw_flap1_degrees', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fw_flap2_degrees', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rw_flap1_degrees', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rw_flap2_degrees', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('drs', models.BooleanField(default=True)),
                ('mode', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cont_current_p', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('peak_current_p', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('kp_current', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('ti_current', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('kp_speed', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('ti_speed', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('event', models.TextField(choices=[('Acceleration', 'Acceleration'), ('Skid Pad', 'Skid Pad'), ('Autocross', 'Autocross'), ('Endurance', 'Endurance')], default='Acceleration')),
                ('comments', models.TextField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Autocross',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('length_lap', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.CreateModel(
            name='Endurance',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('length_lap', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.CreateModel(
            name='SkidPad',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('l1_time', models.DurationField()),
                ('l2_time', models.DurationField()),
                ('r1_time', models.DurationField()),
                ('r2_time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.AddField(
            model_name='testing',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='driver', to='testing.Driver'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='testing',
            order_with_respect_to='date',
        ),
    ]
