# Generated by Django 2.0.2 on 2018-03-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceleration',
            name='params',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='params', to='testing.Testing'),
            preserve_default=False,
        ),
    ]
