# Generated by Django 2.0.2 on 2018-04-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap_time',
            fields=[
                ('temp_inv_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('temp_inv_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('temp_bat_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('temp_bat_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('temp_pneu_FL_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_FR_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_RL_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_RR_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_FL_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_FR_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_RL_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_pneu_RR_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_motor_ini', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('temp_motor_end', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('volt_min_ini', models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True)),
                ('volt_min_end', models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True)),
                ('comments', models.TextField(blank=True, default='', max_length=20000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DecimalField(decimal_places=3, default='', max_digits=6)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_bat_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_bat_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_inv_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_inv_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_motor_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_motor_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_FL_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_FL_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_FR_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_FR_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_RL_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_RL_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_RR_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='temp_pneu_RR_ini',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='volt_min_end',
        ),
        migrations.RemoveField(
            model_name='endurance',
            name='volt_min_ini',
        ),
        migrations.AddField(
            model_name='endurance',
            name='number_laps',
            field=models.DecimalField(decimal_places=0, default=11, max_digits=3),
        ),
        migrations.AddField(
            model_name='endurance',
            name='setup_ini',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_ini', to='testing.Testing'),
        ),
        migrations.AddField(
            model_name='endurance',
            name='setup_mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_mid', to='testing.Testing'),
        ),
        migrations.AddField(
            model_name='testing',
            name='antiroll_bar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='testing',
            name='roll_bar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_bat_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_bat_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_inv_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_inv_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_motor_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_motor_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_FL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_FL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_FR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_FR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_RL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_RL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_RR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='temp_pneu_RR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='volt_min_end',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='volt_min_ini',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_bat_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_bat_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_inv_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_inv_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_motor_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_motor_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_FL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_FL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_FR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_FR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_RL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_RL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_RR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='temp_pneu_RR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=7),
        ),
        migrations.AlterField(
            model_name='autox',
            name='volt_min_end',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='autox',
            name='volt_min_ini',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='l1_time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='l2_time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='r1_time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='r2_time',
            field=models.DecimalField(decimal_places=3, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_bat_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_bat_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_inv_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_inv_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_motor_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_motor_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_FL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_FL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_FR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_FR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_RL_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_RL_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_RR_end',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='temp_pneu_RR_ini',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='volt_min_end',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skid_pad',
            name='volt_min_ini',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='endurance',
            name='time_lap',
            field=models.ManyToManyField(related_name='endurance', to='testing.Lap_time'),
        ),
    ]
