# Generated by Django 2.0.2 on 2018-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AerodynamicsParams',
        ),
        migrations.DeleteModel(
            name='DynamicParams',
        ),
        migrations.DeleteModel(
            name='PowertrainParams',
        ),
        migrations.AddField(
            model_name='testing',
            name='comments',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='testing',
            name='cont_current_p',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='drs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testing',
            name='front_camber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='front_pressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='front_toe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='front_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='testing',
            name='fw_flap1_degrees',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='fw_flap2_degrees',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='kp_current',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='testing',
            name='kp_speed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='testing',
            name='mode',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='testing',
            name='peak_current_p',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='rear_camber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='rear_pressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='rear_toe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='rear_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='testing',
            name='rw_flap1_degrees',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='rw_flap2_degrees',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='testing',
            name='ti_current',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='testing',
            name='ti_speed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.DecimalField(decimal_places=1, default=170, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=4),
        ),
    ]
