# Generated by Django 2.0.2 on 2018-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20180320_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='time',
            new_name='when',
        ),
        migrations.AddField(
            model_name='testing',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=models.SET('Ghost driver'), related_query_name='driver', to='testing.Driver'),
        ),
        migrations.AddField(
            model_name='testing',
            name='front_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='testing',
            name='rear_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.TextField(choices=[(None, 'Select a gender'), ('M', 'Male'), ('F', 'Female')], default=None),
        ),
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='testing',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=20000),
        ),
    ]
