# Generated by Django 2.0.2 on 2018-03-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20180324_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='when',
            new_name='date',
        ),
    ]
