# Generated by Django 2.0.2 on 2018-03-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20180324_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('time', models.TimeField()),
                ('length', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='testing',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='driver', to='testing.Driver'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='event', to='testing.Event'),
        ),
    ]
