# Generated by Django 2.0.2 on 2018-03-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20180326_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.CreateModel(
            name='Autocross',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('length_lap', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.CreateModel(
            name='Endurance',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('length_lap', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.CreateModel(
            name='SkidPad',
            fields=[
                ('testing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testing.Testing')),
                ('l1_time', models.DurationField()),
                ('l2_time', models.DurationField()),
                ('r1_time', models.DurationField()),
                ('r2_time', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
            bases=('testing.testing',),
        ),
        migrations.AlterField(
            model_name='testing',
            name='event',
            field=models.TextField(choices=[('Acceleration', 'Acceleration'), ('Skid Pad', 'Skid Pad'), ('Autocross', 'Autocross'), ('Endurance', 'Endurance')], default='Acceleration'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='testing',
            order_with_respect_to='date',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
