# Generated by Django 2.0.2 on 2018-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20180328_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='time',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='testing',
            name='event',
            field=models.TextField(choices=[('Acceleration', 'Acceleration'), ('SP', 'Skid Pad'), ('Autocross', 'Autocross'), ('Endurance', 'Endurance')], default='Acceleration'),
        ),
    ]
