# Generated by Django 2.0.2 on 2018-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AerodynamicsParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_flap1_degrees', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('fw_flap2_degrees', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('rw_flap1_degrees', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('rw_flap2_degrees', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('drs', models.BooleanField(default=True)),
                ('comments', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, default='', max_digits=4)),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='M')),
                ('birthday', models.DateField()),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_camber', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('rear_camber', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('front_toe', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('rear_toe', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('front_pressure', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('rear_pressure', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('front_weight', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('rear_weight', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('comments', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PowertrainParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.DecimalField(decimal_places=0, default='', max_digits=2)),
                ('cont_current_p', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('peak_current_p', models.DecimalField(decimal_places=1, default='', max_digits=3)),
                ('kp_current', models.DecimalField(decimal_places=0, default='', max_digits=5)),
                ('ti_current', models.DecimalField(decimal_places=0, default='', max_digits=5)),
                ('kp_speed', models.DecimalField(decimal_places=0, default='', max_digits=5)),
                ('ti_speed', models.DecimalField(decimal_places=0, default='', max_digits=5)),
                ('comments', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('event', models.TextField(choices=[('Acceleration', 'Acceleration'), ('Skid Pad', 'Skid Pad'), ('Autocross', 'Autocross'), ('Endurance', 'Endurance')], default='Acceleration')),
            ],
        ),
    ]
