# Generated by Django 2.0.2 on 2018-03-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='born',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='registered_data',
        ),
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='driver',
            name='height',
            field=models.DecimalField(decimal_places=1, default=170, max_digits=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_data',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='registration day'),
        ),
        migrations.AddField(
            model_name='driver',
            name='surname',
            field=models.CharField(default='A', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='M'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(default='A', max_length=200),
        ),
    ]
