# Generated by Django 2.0.2 on 2018-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180306_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthday',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='registration_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
