# Generated by Django 2.0.2 on 2018-03-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180306_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='registration_data',
            new_name='creation',
        ),
    ]
